name: Run Jest Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Upload Jest Coverage Report (optional)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage-report
          path: coverage/