name: Run Jest Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
      - run: npm install
      - run: npm run test

